[I 15:42:53.382 NotebookApp] Serving notebooks from local directory: /gpfs/home4/zimmer/neutrino_clustering_V2
[I 15:42:53.382 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 15:42:53.382 NotebookApp] http://localhost:5040/?token=55fb119ff7e8d7ac33a0080af65e690c44627c79d6ee0596
[I 15:42:53.382 NotebookApp]  or http://127.0.0.1:5040/?token=55fb119ff7e8d7ac33a0080af65e690c44627c79d6ee0596
[I 15:42:53.382 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:42:53.390 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///gpfs/home4/zimmer/.local/share/jupyter/runtime/nbserver-1058640-open.html
    Or copy and paste one of these URLs:
        http://localhost:5040/?token=55fb119ff7e8d7ac33a0080af65e690c44627c79d6ee0596
     or http://127.0.0.1:5040/?token=55fb119ff7e8d7ac33a0080af65e690c44627c79d6ee0596
[I 15:44:06.915 NotebookApp] 302 GET /?token=55fb119ff7e8d7ac33a0080af65e690c44627c79d6ee0596 (::1) 0.410000ms
[I 15:46:37.212 NotebookApp] Creating new notebook in 
[I 15:46:37.362 NotebookApp] Kernel started: a36e92d4-1fb7-48d1-9992-e5ee840ebb38, name: python3
[W 15:46:37.460 NotebookApp] delete /baryons-jvsc-71ab2489-f553-4a0a-8a41-aedc6efaf9e9065c2288-e52a-49ec-8c1f-6f66b9922cab.ipynb
[W 15:46:37.461 NotebookApp] Skipping trash for /gpfs/home4/zimmer/neutrino_clustering_V2/baryons-jvsc-71ab2489-f553-4a0a-8a41-aedc6efaf9e9065c2288-e52a-49ec-8c1f-6f66b9922cab.ipynb, [Errno 13] Permission denied: b'/gpfs/home4/.Trash-59104'
[I 15:46:53.715 NotebookApp] Starting buffering for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:7f933886-ce41-4ef7-911c-bf19b1367cb6
[I 15:50:13.869 NotebookApp] Kernel restarted: a36e92d4-1fb7-48d1-9992-e5ee840ebb38
[I 15:50:13.874 NotebookApp] Starting buffering for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:01620585-928f-4b2c-970a-dce6ee152c3d
[I 15:50:13.880 NotebookApp] Restoring connection for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:01620585-928f-4b2c-970a-dce6ee152c3d
[I 15:51:57.416 NotebookApp] Kernel restarted: a36e92d4-1fb7-48d1-9992-e5ee840ebb38
[I 15:51:57.421 NotebookApp] Starting buffering for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:01620585-928f-4b2c-970a-dce6ee152c3d
[I 15:51:57.426 NotebookApp] Restoring connection for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:01620585-928f-4b2c-970a-dce6ee152c3d
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
Traceback (most recent call last):
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 2159, in _complete
    for m in matcher(text)])
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1713, in dict_key_matches
    keys = self._get_keys(obj)
  File "/home/zimmer/.local/lib/python3.9/site-packages/IPython/core/completer.py", line 1643, in _get_keys
    return method()
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/base.py", line 467, in _ipython_key_completions_
    return sorted(self.keys())
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/_collections_abc.py", line 805, in __len__
    return len(self._mapping)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zimmer/.conda/envs/neutrino_clustering/lib/python3.9/site-packages/h5py/_hl/group.py", line 466, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
ValueError: Invalid group (or file) id (invalid group (or file) ID)
[I 16:15:25.689 NotebookApp] Starting buffering for a36e92d4-1fb7-48d1-9992-e5ee840ebb38:01620585-928f-4b2c-970a-dce6ee152c3d
slurmstepd: error: *** JOB 1778745 ON tcn341 CANCELLED AT 2022-11-01T21:42:42 DUE TO TIME LIMIT ***
