Traceback (most recent call last):
  File "/home/fzimmer/maria/maria_neutrino_clustering/neutrino_clustering/sim_script2_execute_no_gravity.py", line 183, in <module>
    nu_vectors = jnp.array([future.result() for future in futures])
  File "/home/fzimmer/maria/maria_neutrino_clustering/neutrino_clustering/sim_script2_execute_no_gravity.py", line 183, in <listcomp>
    nu_vectors = jnp.array([future.result() for future in futures])
  File "/home/fzimmer/.conda/envs/neutrino_clustering/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/fzimmer/.conda/envs/neutrino_clustering/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
slurmstepd: error: Detected 1 oom_kill event in StepId=5706805.batch. Some of the step tasks have been OOM Killed.
